[default]
forge = "gitea"


[default.gitea]
#host = ""
#api_key = ""
#username = ""
#password = ""

[default.github]
#host = "https://api.github.com/"
#api_key = ""
#username = ""

[default.system]
base_dir = "/tmp/" # Location where git repositories will be cloned into
admin_email = "foo@a.com" # Committing email
job_runner_delay = 1  ## in seconds
northstar = "https://northstar.forgefed.io" # Default discovery service URL
cache_ttl = 3600 # in seconds

[default.server]
url = "http://localhost:7000" # URL at which this interface will run

[testing]
forge = "gitea"

[testing.gitea]
host = "https://git.batsense.net"
api_key = "fakekey1232123"
username = "bot"
password = "password1234"

[testing.github]
#host = "https://api.github.com/"
#api_key = ""
#username = ""

[testing.system]
base_dir = "/tmp/" # Location where git repositories will be cloned into
admin_email = "foo@a.com" # Committing email
job_runner_delay = 1  ## in seconds
northstar = "https://northstar.forgeflux.org" # Default discovery service URL
cache_ttl = 1 # in seconds

[testing.server]
url = "http://localhost:7000" # URL at which this interface will run
