name: Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - nightly

    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            libgit/target
          key: ${{ runner.os }}-cargo-${{ matrix.version }}

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
          profile: minimal
          components: llvm-tools-preview
          override: true

      - name: Install virtualenv
        run: pip install virtualenv

      - name: Create virtualenv
        run: virtualenv venv 

      - name: Install dependencies
        run: make env

      - name: generate coverage
        run: make coverage
        env:
          DYNACONF_GITEA__HOST : "https://git.batsense.net"
          DYNACONF_GITEA__API_KEY : ${{ secrets.DYNACONF_GITEA__API_KEY }}
          DYNACONF_GITEA__USERNAME : ${{ secrets.DYNACONF_GITEA__USERNAME }}
          DYNACONF_GITEA__PASSWORD : ${{ secrets.DYNACONF_GITEA__PASSWORD }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./libgit/target/lcov.info,coverage.xml
